# Basic linear algebra

In [2]:
A = rand(1:4, 3, 3) #rand from 1 to 4 as int, 3x3 matrix

3×3 Matrix{Int64}:
 4  1  4
 2  1  2
 3  3  1

In [3]:
B = A #not creating a new matrix but a pointer to A
C = copy(A)
[B C] #side by side

3×6 Matrix{Int64}:
 4  1  4  4  1  4
 2  1  2  2  1  2
 3  3  1  3  3  1

In [4]:
# watch out!
# B and A share the same memory
A[1] = 17
[B C]

3×6 Matrix{Int64}:
 17  1  4  4  1  4
  2  1  2  2  1  2
  3  3  1  3  3  1

In [5]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [15]:
b = A * x

3-element Vector{Float64}:
 22.0
  5.0
  7.0

In [8]:
# transpose -> A'
Asym = A + A'

3×3 Matrix{Int64}:
 34  3  7
  3  2  5
  7  5  2

In [9]:
# transposed multiplciation doesn't require the *
Apd = A'A

3×3 Matrix{Int64}:
 302  28  75
  28  11   9
  75   9  21

In [10]:
# solve linear systems
# The problems Ax = b is solved by
# It's simple

A\b

3-element Vector{Float64}:
 1.0
 1.0000000000000002
 1.0

In [11]:
# overdetermined systems
# 3 equations 2 unknowns

Atall = A[:, 1:2] #a tall skinny version of matrix A
display(Atall)
Atall\b #give minimum norm solution

3×2 Matrix{Int64}:
 17  1
  2  1
  3  3

2-element Vector{Float64}:
 1.2257683215130024
 1.243498817966903

In [17]:
A = randn(3,3)

3×3 Matrix{Float64}:
 -0.554085   0.204295   0.913457
  0.416101  -1.09999   -0.553221
 -1.15482    0.376122   0.825358

In [18]:
display([A[:, 1] A[:, 1]])
[A[:, 1] A[:, 1]] \ b

3×2 Matrix{Float64}:
 -0.554085  -0.554085
  0.416101   0.416101
 -1.15482   -1.15482

2-element Vector{Float64}:
 -5.0153054929520575
 -5.015305492952058

In [20]:
# underdetermined systems
# 2 equations 3 unkonwns
Ashort = A[1:2, :]
display(Ashort)
Ashort \ b[1:2] # give minimum norm solution


2×3 Matrix{Float64}:
 -0.554085   0.204295   0.913457
  0.416101  -1.09999   -0.553221

3-element Vector{Float64}:
 -11.152064470078287
 -19.68936097426662
  21.723247225016785