# Factorization and other fun

In [1]:
A = randn(3, 3)

3×3 Matrix{Float64}:
 -0.261552   0.0204189  -0.175613
 -0.0922646  0.340751    0.108116
  0.364899   0.130434    0.493947

In [50]:
using LinearAlgebra
import Pkg

┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Downloads.RequestError("https://pkg.julialang.org/registries", 28, "Connection timeout after 30001 ms", Downloads.Response("https", "https://cn-northeast.pkg.juliacn.com/registries", 301, "HTTP/2 301", ["server" => "Varnish", "retry-after" => "0", "location" => "https://cn-northeast.pkg.juliacn.com/registries", "x-geo-continent" => "AS", "x-geo-country" => "CN", "x-geo-region" => "BJ", "accept-ranges" => "bytes", "date" => "Thu, 24 Aug 2023 07:48:16 GMT", "via" => "1.1 varnish", "x-served-by" => "cache-tyo11950-TYO", "x-cache" => "HIT", "x-cache-hits" => "0", "x-timer" => "S1692863296.118903,VS0,VE0", "content-length" => "0"]))
└ @ Pkg.Registry /home/peiyuan/.julia/juliaup/julia-1.9.2+0.x64.linux.gnu/share/julia/stdlib/v1.9/Pkg/src/Registry/Registry.jl:69
    Updating registry at `~/.julia/registries/General`
    Updating

 git-repo `https://github.com/JuliaRegistries/General.git`


Pkg.Types.PkgError: The following package names could not be resolved:
 * Factorization (not found in project, manifest or registry)
   Suggestions: LDLFactorizations BlockFactorizations TakagiFactorization

In [7]:
#LU decomposition: function LU
#returns L,U and permutation vector p
l,u, p = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0       0.0       0.0
 -0.25285   1.0       0.0
 -0.716779  0.304794  1.0
U factor:
3×3 Matrix{Float64}:
 0.364899  0.130434  0.493947
 0.0       0.373731  0.233011
 0.0       0.0       0.107418

In [10]:
#pivoting is on by default so we can't assume A=LU
display(norm(l * u - A))
display(p)
display(A[p,:])
display(norm(l * u - A[p, :]))

1.3060273231867978

3-element Vector{Int64}:
 3
 2
 1

3×3 Matrix{Float64}:
  0.364899   0.130434    0.493947
 -0.0922646  0.340751    0.108116
 -0.261552   0.0204189  -0.175613

2.2215299868541707e-17

In [52]:
#turn the pivoting off
l,u,p = lu(A, Val(false))
norm(l*u-A)

1.4275043794430723e-9

In [19]:
#Another lu factorization
Alu = lufact(A)
#we haven't got lufact etc. nowadays in the latest version in julia?

UndefVarError: UndefVarError: `lufact` not defined

In [ ]:
#Then call the matrices
Alu[:P]
Alu[:L]
alu[:U]

In [20]:
x = ones(3)
b = A * x

3-element Vector{Float64}:
 -0.41674559877439304
  0.3566027170822189
  0.9892795051101153

In [12]:
det(A)

-1.1056746877448151

In [21]:
A\b

3-element Vector{Float64}:
 0.9999999999999996
 0.9999999999999994
 1.0000000000000004

In [26]:
#the qr factorization
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.570653  -0.092918   0.815917
 -0.201303  -0.947434  -0.248687
  0.796136  -0.30616    0.521952
R factor:
3×3 Matrix{Float64}:
 0.458337   0.0235967   0.471699
 0.0       -0.36467    -0.237343
 0.0        0.0         0.0876439

In [32]:
Asym = A + A'
Asymeig = eigen(Asym) #colomns are eigvecs

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.5548513307200118
  0.5721796277577124
  1.1289648100639018
vectors:
3×3 Matrix{Float64}:
 -0.987475    0.135134  0.0814375
 -0.0832436  -0.884702  0.458664
  0.134029    0.44614   0.88487

In [55]:
typeof(Asymeig) #it's a type call eigen

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.5548513307200118
  0.5721796277577124
  1.1289648100639018
vectors:
3×3 Matrix{Float64}:
 -0.987475    0.135134  0.0814375
 -0.0832436  -0.884702  0.458664
  0.134029    0.44614   0.88487

In [61]:
A = rand(3,3)
uu = eigvals(A)
vv = eigvecs(A)

3×3 Matrix{Float64}:
 -0.770006  -0.122313  -0.65513
  0.242976  -0.714519  -0.60047
  0.589961   0.688841  -0.45852

In [62]:
uu

3-element Vector{Float64}:
 -0.4473753260148712
  0.36015033380003325
  1.8914127412202515

In [63]:
vv

3×3 Matrix{Float64}:
 -0.770006  -0.122313  -0.65513
  0.242976  -0.714519  -0.60047
  0.589961   0.688841  -0.45852

In [64]:
#check colomn as eigvecs
println("should be zero", norm(A*vv[:,1]-uu[1]*vv[:,1]))

should be zero2.7894008272968645e-16


In [36]:
Asvd = svd(A[:, 1:2])

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×2 Matrix{Float64}:
 -0.557149  -0.154479
 -0.096983  -0.963716
  0.82473   -0.217686
singular values:
2-element Vector{Float64}:
 0.45996958563849233
 0.36337610873711
Vt factor:
2×2 Matrix{Float64}:
 0.990531   0.13729
 0.13729   -0.990531

In [65]:
u,s,v = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.665792   0.532856    0.522289
 -0.579695   0.0712961  -0.811709
 -0.469761  -0.843197    0.261425
singular values:
3-element Vector{Float64}:
 1.919532907444103
 0.5675389976892561
 0.27973762869532626
Vt factor:
3×3 Matrix{Float64}:
 -0.59975   -0.524833  -0.604029
 -0.666031   0.745805   0.0132931
 -0.443511  -0.410275   0.796852

In [37]:
Asvd \ b

2-element Vector{Float64}:
 1.9956448880114765
 1.6508414163321017

In [66]:
A

3×3 Matrix{Float64}:
 0.500268  0.836342   0.892397
 0.741124  0.707341   0.491729
 0.827101  0.0863466  0.596579

In [68]:
diag(A) #grab the diagonal elements to form a vector

3-element Vector{Float64}:
 0.5002681820567907
 0.7073407063595061
 0.5965788605891182

In [67]:
Diagonal(diag(A)) #take the diagonal elements to form a new matrix

3×3 Diagonal{Float64, Vector{Float64}}:
 0.500268   ⋅         ⋅ 
  ⋅        0.707341   ⋅ 
  ⋅         ⋅        0.596579

In [69]:
Diagonal(A)

3×3 Diagonal{Float64, Vector{Float64}}:
 0.500268   ⋅         ⋅ 
  ⋅        0.707341   ⋅ 
  ⋅         ⋅        0.596579

In [70]:
LowerTriangular(A)

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 0.500268   ⋅          ⋅ 
 0.741124  0.707341    ⋅ 
 0.827101  0.0863466  0.596579

In [72]:
Symmetric(A) #take the upper triang to get the symmetric one

3×3 Symmetric{Float64, Matrix{Float64}}:
 0.500268  0.836342  0.892397
 0.836342  0.707341  0.491729
 0.892397  0.491729  0.596579

In [74]:
diag(A,1) #the second diag line of matrix A

2-element Vector{Float64}:
 0.8363421172750903
 0.49172904586824107

In [75]:
SymTridiagonal(diag(A), diag(A, 1))

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 0.500268  0.836342   ⋅ 
 0.836342  0.707341  0.491729
  ⋅        0.491729  0.596579

In [43]:
n = 1000
A = randn(n, n)
Asym1 = A + A'
Asym2 = copy(Asym1)
Asym2[1, 2] += 5eps()
println("Is Asym1 symmetric? ", issymmetric(Asym1))
println("Is Asym2 symmetric? ", issymmetric(Asym2))

Is Asym1 symmetric? true
Is Asym2 symmetric? false


In [44]:
@time eigvals(Asym1)

  0.521913 seconds (274.82 k allocations: 26.223 MiB, 2.03% gc time, 73.93% compilation time)


1000-element Vector{Float64}:
 -88.86417605558447
 -88.06810225658336
 -87.48246186050066
 -87.00279838994159
 -86.47041613776459
 -85.7573853455494
 -85.52501983314819
 -85.22857538879232
 -84.98451338496787
 -84.09866821710227
   ⋮
  83.92726418903
  84.2477896000978
  84.51535993075244
  84.90229661187408
  85.18611192165794
  86.36581636026717
  86.51635437818271
  87.0053679832138
  88.35879190958138

In [45]:
@time eigvals(Asym2)

  0.647067 seconds (14 allocations: 7.928 MiB)


1000-element Vector{Float64}:
 -88.86417605558412
 -88.06810225658324
 -87.48246186050211
 -87.00279838994234
 -86.47041613776511
 -85.75738534554922
 -85.52501983314866
 -85.228575388792
 -84.98451338496832
 -84.09866821710176
   ⋮
  83.92726418902993
  84.24778960009763
  84.51535993075254
  84.90229661187436
  85.18611192165764
  86.36581636026662
  86.51635437818149
  87.00536798321296
  88.35879190958211

In [46]:
@time eigvals(Symmetric(Asym2))

  0.168115 seconds (59.53 k allocations: 12.032 MiB, 36.84% compilation time)


1000-element Vector{Float64}:
 -88.86417605558375
 -88.06810225658276
 -87.48246186050088
 -87.00279838994078
 -86.47041613776486
 -85.75738534554988
 -85.52501983314829
 -85.2285753887911
 -84.98451338496746
 -84.09866821710263
   ⋮
  83.92726418903112
  84.24778960009806
  84.5153599307529
  84.90229661187368
  85.18611192165794
  86.36581636026729
  86.51635437818244
  87.00536798321338
  88.35879190958131

### Example 1: rational linear system of equations
Julia has rational numbers built in. The following example shows how a linear system of equations can be solved without promoting to floating point element types. Overflow can easily become a problem when working with rational numbers so we use "Bigint"

In [76]:
Ar = convert(Matrix{Rational{BigInt}}, rand(1:10, 3, 3)) / 10

3×3 Matrix{Rational{BigInt}}:
 4//5  3//10  1//10
 1//1  1//5   3//10
 1//1  1//5   1//10

In [48]:
x = ones(Int, 3)
b = Ar * x

3-element Vector{Rational{BigInt}}:
  9//10
 19//10
  6//5

In [77]:
l,u,p = lu(Ar)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  0//1  0//1
 4//5  1//1  0//1
 1//1  0//1  1//1
U factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  1//5    3//10
 0//1  7//50  -7//50
 0//1  0//1   -1//5

In [78]:
Ar\b

3-element Vector{Rational{BigInt}}:
  29//28
 -13//14
   7//2

In [79]:
float(Ar\b) #turn the rational number into float

3-element Vector{BigFloat}:
  1.035714285714285714285714285714285714285714285714285714285714285714285714285709
 -0.9285714285714285714285714285714285714285714285714285714285714285714285714285727
  3.5

### Example 2: rational matrix from eigenstructure

This example shows how rational matrix arithmetic can be used for calculating a matrix given rational eigenvalues and vectors. 

In [87]:
lamb1, lamb2, lamb3 = 1//1, 1//2, 1//4
v1, v2, v3 = [1,0,0],[1,1,0],[1,1,1]
v, Lamb = [v1 v2 v3], Diagonal([lamb1,lamb2,lamb3]) #don't add commas between v1,v2,v3, that's a vector(list). But we need a matrix
display(v)
display(Lamb)

3×3 Matrix{Int64}:
 1  1  1
 0  1  1
 0  0  1

3×3 Diagonal{Rational{Int64}, Vector{Rational{Int64}}}:
 1//1   ⋅     ⋅  
  ⋅    1//2   ⋅  
  ⋅     ⋅    1//4

In [88]:
A = v*Lamb/v

3×3 Matrix{Rational{Int64}}:
 1//1  -1//2  -1//4
 0//1   1//2  -1//4
 0//1   0//1   1//4