# Basic linear algebra

In [2]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 2  4  1
 1  4  1
 2  4  4

In [3]:
B = A
C = copy(A)
[B C]

3×6 Matrix{Int64}:
 2  4  1  2  4  1
 1  4  1  1  4  1
 2  4  4  2  4  4

In [4]:
# watch out!
A[1] = 17
[B C]

3×6 Matrix{Int64}:
 17  4  1  2  4  1
  1  4  1  1  4  1
  2  4  4  2  4  4

In [5]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [6]:
b = A * x

3-element Vector{Float64}:
 22.0
  6.0
 10.0

In [7]:
# transpose -> A'
Asym = A + A'

3×3 Matrix{Int64}:
 34  5  3
  5  8  5
  3  5  8

In [8]:
# transposed multiplciation doesn't require the *
Apd = A'A

3×3 Matrix{Int64}:
 294  80  26
  80  48  24
  26  24  18

In [9]:
# solve linear systems
# The problems Ax = b is solved by

A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [10]:
# overdetermined systems

Atall = A[:, 1:2]
display(Atall)
Atall\b

3×2 Matrix{Int64}:
 17  4
  1  4
  2  4

2-element Vector{Float64}:
 0.9128630705394183
 1.6452282157676352

In [11]:
A = randn(3,3)

3×3 Matrix{Float64}:
 -0.127535   1.46096   -0.427948
 -0.487198  -0.264527  -0.636332
  1.78368   -1.00151    1.61821

In [13]:
[A[:, 1] A[:, 1]] \ b

2-element Vector{Float64}:
 1.7623522622935575
 1.762352262293557

In [15]:
# underdetermined systems

Ashort = A[1:2, :]
display(Ashort)
Ashort \ b[1:2]

2×3 Matrix{Float64}:
 -0.127535   1.46096   -0.427948
 -0.487198  -0.264527  -0.636332

3-element Vector{Float64}:
 -5.674906760732092
 11.654776918556653
 -9.929083902361821