# Factorization and other fun

In [1]:
A = randn(3, 3)

3×3 Matrix{Float64}:
 -0.284254   1.34786    0.348285
 -1.46454   -0.560375   0.923598
 -0.602762  -1.70215   -0.308921

In [8]:
using LinearAlgebra

In [7]:
l,u, p = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.411572   1.0       0.0
 0.194091  -0.989882  1.0
U factor:
3×3 Matrix{Float64}:
 -1.46454  -0.560375   0.923598
  0.0      -1.47151   -0.689048
  0.0       0.0       -0.513055

In [5]:
display(norm(l * u - A))
display(norm(l * u - A[p, :]))

4.332054485826372

5.551115123125783e-17

In [11]:
x = ones(3)
b = A * x

3-element Vector{Float64}:
  1.4118891449708215
 -1.101312669380945
 -2.6138282272606794

In [12]:
det(A)

-1.1056746877448151

In [13]:
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.176661   0.736033   0.653488
 -0.910196   0.130526  -0.393072
 -0.374611  -0.664243   0.646876
R factor:
3×3 Matrix{Float64}:
 1.60903  0.909579  -0.786459
 0.0      2.04956    0.582101
 0.0      0.0       -0.335275

In [14]:
Asym = A + A'
eigen(Asym)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -1.7388416304725516
 -0.5533848690128936
 -0.014874266642381293
vectors:
3×3 Matrix{Float64}:
 -0.206022   0.944564  -0.255645
 -0.781192  -0.316093  -0.538353
 -0.589316   0.088795   0.803008

In [15]:
Asvd = svd(A[:, 1:2])

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×2 Matrix{Float64}:
  0.460202   0.600973
 -0.472191   0.789006
 -0.751831  -0.127678
singular values:
2-element Vector{Float64}:
 2.3903057368656206
 1.3796620670241715
Vt factor:
2×2 Matrix{Float64}:
  0.424172  0.905581
 -0.905581  0.424172

In [16]:
Asvd \ b

2-element Vector{Float64}:
 0.35067175979073706
 1.2840123408297102

In [17]:
Diagonal(diag(A))

3×3 Diagonal{Float64, Vector{Float64}}:
 -0.284254    ⋅          ⋅ 
   ⋅        -0.560375    ⋅ 
   ⋅          ⋅        -0.308921

In [18]:
Diagonal(A)

3×3 Diagonal{Float64, Vector{Float64}}:
 -0.284254    ⋅          ⋅ 
   ⋅        -0.560375    ⋅ 
   ⋅          ⋅        -0.308921

In [19]:
LowerTriangular(A)

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 -0.284254    ⋅          ⋅ 
 -1.46454   -0.560375    ⋅ 
 -0.602762  -1.70215   -0.308921

In [20]:
Symmetric(Asym)

3×3 Symmetric{Float64, Matrix{Float64}}:
 -0.568508  -0.116677  -0.254477
 -0.116677  -1.12075   -0.778547
 -0.254477  -0.778547  -0.617843

In [21]:
SymTridiagonal(diag(Asym), diag(Asym, 1))

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 -0.568508  -0.116677    ⋅ 
 -0.116677  -1.12075   -0.778547
   ⋅        -0.778547  -0.617843

In [22]:
n = 1000
A = randn(n, n)
Asym1 = A + A'
Asym2 = copy(Asym1)
Asym2[1, 2] += 5eps()
println("Is Asym1 symmetric? ", issymmetric(Asym1))
println("Is Asym2 symmetric? ", issymmetric(Asym2))

Is Asym1 symmetric? true
Is Asym2 symmetric? false


In [24]:
@time eigvals(Asym1)

  0.033334 seconds (11 allocations: 7.989 MiB)


1000-element Vector{Float64}:
 -87.84270769969473
 -87.4324143989015
 -86.92275506424438
 -86.87304332615322
 -85.34600110114236
 -84.74407317761087
 -84.37540230501796
 -84.21107740062789
 -83.98041133835721
 -83.83756297144944
 -83.73529296483625
 -82.83057830614393
 -82.58661601020194
   ⋮
  83.3758593190869
  83.76047236879162
  83.81929508728271
  84.3994775228479
  85.01404148971623
  85.76185126815534
  86.03759455318797
  86.20255755512649
  86.73922114595227
  87.27557174152776
  88.30767378826799
  89.56030393430737

In [23]:
@time eigvals(Asym2)

  0.506980 seconds (274.83 k allocations: 26.163 MiB, 46.83% compilation time)


1000-element Vector{Float64}:
 -87.84270769969544
 -87.43241439890232
 -86.92275506424447
 -86.87304332615328
 -85.34600110114286
 -84.74407317761192
 -84.37540230501827
 -84.21107740062901
 -83.98041133835753
 -83.83756297144933
 -83.73529296483589
 -82.83057830614449
 -82.58661601020172
   ⋮
  83.37585931908723
  83.7604723687931
  83.8192950872833
  84.39947752284748
  85.01404148971615
  85.76185126815652
  86.03759455318753
  86.20255755512687
  86.73922114595216
  87.27557174152813
  88.30767378826904
  89.56030393430804

In [25]:
@time eigvals(Symmetric(Asym2))

  0.081119 seconds (58.68 k allocations: 11.974 MiB, 9.18% gc time, 58.52% compilation time)


1000-element Vector{Float64}:
 -87.84270769969524
 -87.4324143989015
 -86.9227550642439
 -86.87304332615297
 -85.34600110114229
 -84.74407317761091
 -84.37540230501838
 -84.21107740062844
 -83.98041133835723
 -83.83756297144872
 -83.73529296483609
 -82.83057830614455
 -82.58661601020214
   ⋮
  83.37585931908784
  83.7604723687921
  83.81929508728291
  84.3994775228474
  85.01404148971554
  85.76185126815572
  86.03759455318678
  86.20255755512628
  86.73922114595179
  87.27557174152747
  88.30767378827008
  89.56030393430663

In [27]:
Ar = convert(Matrix{Rational{BigInt}}, rand(1:10, 3, 3)) / 10

3×3 Matrix{Rational{BigInt}}:
 1//2  2//5   1//1
 1//5  1//10  3//5
 1//1  3//5   1//10

In [28]:
x = ones(Int, 3)
b = Ar * x

3-element Vector{Rational{BigInt}}:
 19//10
  9//10
 17//10