# Loops

# while loops

In [2]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
myfriends = ["naruto", "sasuke", "sakura"]

i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you")
    i += 1
end

Hi naruto, it's great to see you
Hi sasuke, it's great to see you
Hi sakura, it's great to see you


# for loops

In [5]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [6]:
myfriends = ["naruto", "sasuke", "sakura"]

for friend in myfriends
    println("Hi $friend, great to see you")
end

Hi naruto, great to see you
Hi sasuke, great to see you
Hi sakura, great to see you


In [9]:
# there are others syntax
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [10]:
m, n = 5, 5
A = zeros(m, n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [11]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [14]:
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [15]:
# array comprehension
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10